export const FETCH_APPROACH_REQUEST = 'FETCH_APPROACH_REQUEST';
export const FETCH_APPROACH_SUCCESS = 'FETCH_APPROACH_SUCCESS';
export const FETCH_APPROACH_FAILURE = 'FETCH_APPROACH_FAILURE';
export const SELECT_APPROACH_TO_EDIT = 'SELECT_APPROACH_TO_EDIT';

