// Hero Types
export const FETCH_HERO_REQUEST = 'FETCH_HERO_REQUEST';
export const FETCH_HERO_SUCCESS = 'FETCH_HERO_SUCCESS';
export const FETCH_HERO_FAILURE = 'FETCH_HERO_FAILURE';
export const SELECT_HERO_TO_EDIT = 'SELECT_HERO_TO_EDIT';
